// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,output_legacy_commonjs
// @generated from protobuf file "post.proto" (package "proto", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from '@protobuf-ts/runtime';
import type { IBinaryWriter } from '@protobuf-ts/runtime';
import { WireType } from '@protobuf-ts/runtime';
import type { BinaryReadOptions } from '@protobuf-ts/runtime';
import type { IBinaryReader } from '@protobuf-ts/runtime';
import { UnknownFieldHandler } from '@protobuf-ts/runtime';
import type { PartialMessage } from '@protobuf-ts/runtime';
import { reflectionMergePartial } from '@protobuf-ts/runtime';
import { MessageType } from '@protobuf-ts/runtime';
/**
 * @generated from protobuf message proto.PostCreated
 */
export interface PostCreated {
  /**
   * @generated from protobuf field: int32 id = 1;
   */
  id: number;
  /**
   * @generated from protobuf field: string title = 2;
   */
  title: string;
  /**
   * @generated from protobuf field: int32 authorId = 3;
   */
  authorId: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class PostCreated$Type extends MessageType<PostCreated> {
  constructor() {
    super('proto.PostCreated', [
      { no: 1, name: 'id', kind: 'scalar', T: 5 /*ScalarType.INT32*/ },
      { no: 2, name: 'title', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      { no: 3, name: 'authorId', kind: 'scalar', T: 5 /*ScalarType.INT32*/ },
    ]);
  }
  create(value?: PartialMessage<PostCreated>): PostCreated {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.id = 0;
    message.title = '';
    message.authorId = 0;
    if (value !== undefined)
      reflectionMergePartial<PostCreated>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: PostCreated,
  ): PostCreated {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* int32 id */ 1:
          message.id = reader.int32();
          break;
        case /* string title */ 2:
          message.title = reader.string();
          break;
        case /* int32 authorId */ 3:
          message.authorId = reader.int32();
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: PostCreated,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* int32 id = 1; */
    if (message.id !== 0) writer.tag(1, WireType.Varint).int32(message.id);
    /* string title = 2; */
    if (message.title !== '')
      writer.tag(2, WireType.LengthDelimited).string(message.title);
    /* int32 authorId = 3; */
    if (message.authorId !== 0)
      writer.tag(3, WireType.Varint).int32(message.authorId);
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message proto.PostCreated
 */
export const PostCreated = new PostCreated$Type();
